/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author keerthanajagana
 */
public class CreateJPanel extends javax.swing.JPanel {
    private Boolean validate = true;
    private DeliveryPackage delPackage;
    

    /**
     * Creates new form CreateJPanel
     */
    
    
    public CreateJPanel() {
        initComponents();
        
    }

    CreateJPanel(DeliveryPackage deliveryPackage) {
        initComponents();
        this.delPackage=deliveryPackage;
        //missing line
        //logic to take info from user and store in dp
         }

    

    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jButton2 = new javax.swing.JButton();
        packageId = new javax.swing.JTextField();
        packageWt = new javax.swing.JTextField();
        productId = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        productPrice = new javax.swing.JTextField();
        custName = new javax.swing.JTextField();
        custId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        btnSave = new javax.swing.JButton();
        saveProductbtn = new javax.swing.JButton();

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("show");

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 80, -1));

        packageWt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageWtActionPerformed(evt);
            }
        });
        add(packageWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 80, -1));

        productId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdActionPerformed(evt);
            }
        });
        add(productId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, 80, -1));
        add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 370, 80, -1));
        add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 420, 80, -1));

        custName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                custNameFocusLost(evt);
            }
        });
        add(custName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 90, -1));
        add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 90, -1));

        jLabel1.setText("Package Id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 56, 80, 30));

        jLabel2.setText("Package Weight");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 136, 100, 20));

        jLabel3.setText("Customer Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 60, 120, -1));

        jLabel4.setText("Customer Id");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 146, 90, 20));

        jLabel5.setText("Product Id");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 330, 80, -1));

        jLabel6.setText("Product Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 100, -1));

        jLabel7.setText("Product Price");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 430, 90, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 190, 120, 30));

        saveProductbtn.setText("Save Product");
        saveProductbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProductbtnActionPerformed(evt);
            }
        });
        add(saveProductbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 410, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void packageWtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageWtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageWtActionPerformed

    private void productIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIdActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        String id = packageId.getText();
        String weight=packageWt.getText();
        
        
        String customerName=custName.getText();
        String customerId=custId.getText();
        
        
        //store the data
        this.delPackage.setPackageID(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Integer.valueOf(weight));
        
//        Product product = this.delPackage.getProduct();
//        product.setProductId(Integer.valueOf(productId1));
//        product.setProductName(prodName);
//        product.setPrice(Integer.valueOf(prodPrice));
        
        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerID(Integer.valueOf(customerId));
        customer.setFullName(customerName);
        
//        JOptionPane.showMessageDialog(null,"created");

if(validate) {
            JOptionPane.showMessageDialog(null, "Pleae fill all fields");
        } else {
            JOptionPane.showMessageDialog(null, "Saved!");
        }
        
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void saveProductbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProductbtnActionPerformed
        // TODO add your handling code here:
        String productId1=productId.getText();
        String productName1=productName.getText();
        String prodPrice=productPrice.getText();
        
        Product product = this.delPackage.createProduct(Integer.valueOf(productId1), productName1, Double.valueOf(prodPrice));
        JOptionPane.showMessageDialog(null, "Added Product");
        
    }//GEN-LAST:event_saveProductbtnActionPerformed

    private void custNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_custNameFocusLost
        // TODO add your handling code here:
        System.out.println(custName.getText() + " -- the customer name");
        String name = custName.getText();
        
        if(name.isEmpty()) {
           // JOptionPane.showMessageDialog(null, "Please fill name");
            this.validate = true;
        } else {
            this.validate = false;
        }
    }//GEN-LAST:event_custNameFocusLost

 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSave;
    private javax.swing.JTextField custId;
    private javax.swing.JTextField custName;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWt;
    private javax.swing.JTextField productId;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productPrice;
    private javax.swing.JButton saveProductbtn;
    // End of variables declaration//GEN-END:variables
}
