/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Customer;
import Model.DeliveryPackage;
import Model.Product;
import javax.swing.JOptionPane;

/**
 *
 * @author keerthanajagana
 * 
 */



public class EditJPanel extends javax.swing.JPanel {

    /**
     * Creates new form EditJPanel
     */
    
    private DeliveryPackage delPackage;
    private Product productViewed;
    private Boolean validate = false;
    public EditJPanel() {
        initComponents();
    }
//    CreateJPanel(DeliveryPackage deliveryPackage) {
//        initComponents();
//        this.delPackage= deliveryPackage;
//        
//        //missing line
//        //logic to take info from user and store in dp
//         }

    EditJPanel(DeliveryPackage deliveryPackage) {
        initComponents();
        this.delPackage=deliveryPackage;
        displayProductList();
        
        displayPackageDetails();

          }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        packageId = new javax.swing.JTextField();
        packageWt = new javax.swing.JTextField();
        productId = new javax.swing.JTextField();
        productName = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        productPrice = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        custName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        custId = new javax.swing.JTextField();
        productComboBox = new javax.swing.JComboBox();
        show = new javax.swing.JButton();
        updateProduct = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 120, 30));

        jLabel1.setText("Package Id");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 56, 80, 30));

        jLabel2.setText("Package Weight");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(35, 136, 100, 20));

        jLabel5.setText("Product Id");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 80, -1));

        jLabel6.setText("Product Name");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 100, -1));
        add(packageId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 80, -1));

        packageWt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packageWtActionPerformed(evt);
            }
        });
        add(packageWt, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 80, -1));

        productId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdActionPerformed(evt);
            }
        });
        add(productId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 270, 80, -1));
        add(productName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, 80, -1));

        jLabel7.setText("Product Price");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 90, -1));
        add(productPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 400, 80, -1));

        jLabel3.setText("Customer Name");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(461, 70, 120, -1));
        add(custName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 60, 90, -1));

        jLabel4.setText("Customer Id");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 146, 90, 20));
        add(custId, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 90, -1));

        add(productComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 100, -1));

        show.setText("Show");
        show.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showActionPerformed(evt);
            }
        });
        add(show, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        updateProduct.setText("Update product");
        updateProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateProductActionPerformed(evt);
            }
        });
        add(updateProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 400, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void packageWtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_packageWtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_packageWtActionPerformed

    private void productIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIdActionPerformed

    private void showActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showActionPerformed
        // TODO add your handling code here:
        productId.setEnabled(false);
        
        int pid=(int) productComboBox.getSelectedItem();
        Product prod = this.delPackage.findProduct(pid);
         this.productViewed = prod;
        // display the product content

        if (!prod.equals(null)) {
            productId.setText(String.valueOf(pid));
            productName.setText(prod.getProductName());
            productPrice.setText(String.valueOf(prod.getPrice()));
        } else {
            JOptionPane.showMessageDialog(null, "Product not found");
        }
        
        
    }//GEN-LAST:event_showActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        String id = packageId.getText();
        String weight=packageWt.getText();
        
        
        String customerName=custName.getText();
        String customerId=custId.getText();
        
        
        //store the data
        this.delPackage.setPackageID(Integer.valueOf(id));
        this.delPackage.setPackageWeight(Integer.valueOf(weight));
        Customer customer = this.delPackage.getCustomer();
        customer.setCustomerID(Integer.valueOf(customerId));
        customer.setFullName(customerName);
        
//        JOptionPane.showMessageDialog(null,"created");


        
    }//GEN-LAST:event_btnEditActionPerformed

    private void updateProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateProductActionPerformed
        // TODO add your handling code here:
        this.productViewed.setProductName(productName.getText());
        this.productViewed.setPrice(Double.valueOf(productPrice.getText()));
    
    }//GEN-LAST:event_updateProductActionPerformed

public void displayProductList() {

        for (Product p : this.delPackage.getProductList()) {
            productComboBox.addItem(p.getProductId());
        }

    }
    public void displayPackageDetails(){
        packageId.setText(String.valueOf(this.delPackage.getPackageID()));
        packageWt.setText(String.valueOf(this.delPackage.getPackageWeight()));
        
        Customer customer=this.delPackage.getCustomer();
        custId.setText(String.valueOf(customer.getCustomerID()));
        custName.setText(customer.getFullName());
        
        //Product product=this.delPackage.getProduct();
        
        
        
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JTextField custId;
    private javax.swing.JTextField custName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField packageId;
    private javax.swing.JTextField packageWt;
    private javax.swing.JComboBox productComboBox;
    private javax.swing.JTextField productId;
    private javax.swing.JTextField productName;
    private javax.swing.JTextField productPrice;
    private javax.swing.JButton show;
    private javax.swing.JButton updateProduct;
    // End of variables declaration//GEN-END:variables
}
