/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI;

import Model.Application;
import Model.VitalSignsHistory;


/**
 *
 * @author keerthanajagana
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    Application application;
    
    public CreateJPanel() {
        initComponents();
    }

    CreateJPanel(Application application) {
        initComponents();
        this.application=application;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        createObservationId = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        temp = new javax.swing.JTextField();
        bloodPressure = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        addObs = new javax.swing.JButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(createObservationId, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 68, 144, -1));

        jLabel1.setText("CREATE A VITAL SIGN");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(206, 6, 162, 35));

        jLabel2.setText("ID");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 73, -1, -1));
        add(temp, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 150, 144, -1));
        add(bloodPressure, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 228, 144, -1));

        jLabel3.setText("TEMPERARTURE");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 155, -1, -1));

        jLabel4.setText("BLOOD PRESSURE");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 238, -1, -1));

        addObs.setText("ADD OBSERVATION");
        addObs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addObsActionPerformed(evt);
            }
        });
        add(addObs, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 358, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addObsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addObsActionPerformed
        // TODO add your handling code here:
        
        VitalSignsHistory history = this.application.getHistory();
        
        //read the fields
        String id =createObservationId.getText();
        String temperature=temp.getText();
        String bloodP=bloodPressure.getText();
        
        history.createObservation(Integer.valueOf(id),Double.valueOf(bloodP),Double.valueOf(temperature));
        
    }//GEN-LAST:event_addObsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addObs;
    private javax.swing.JTextField bloodPressure;
    private javax.swing.JTextField createObservationId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField temp;
    // End of variables declaration//GEN-END:variables
}
